# Configuration file for custom scenarios for `premise`
# Energy Perspective Scenario 2050+
# https://www.bfe.admin.ch/bfe/en/home/policy/energy-perspectives-2050-plus.html/

---

production pathways:
  hydro_run_of_river:
    production volume:
      variable: Production|Electricity|Run-of-river hydro
    ecoinvent alias:
      name: electricity production, hydro, run-of-river
      reference product: electricity, high voltage
      exists in original database: True
 
  hydro_reservoir:
    production volume:
      variable: Production|Electricity|Reservoir
    ecoinvent alias:
      name: electricity production, hydro, reservoir, alpine region
      reference product: electricity, high voltage
      exists in original database: True

  nuclear_boiling_water:
    production volume:
      variable: Production|Electricity|Nuclear|Boiling water reactor
    ecoinvent alias:
      name: electricity production, nuclear, boiling water reactor
      reference product: electricity, high voltage
      exists in original database: True

  nuclear_pressure_water:
    production volume:
      variable: Production|Electricity|Nuclear|Pressure water reactor
    ecoinvent alias:
      name: electricity production, nuclear, pressure water reactor
      reference product: electricity, high voltage
      exists in original database: True

  conventional_waste:
    production volume:
      variable: Production|Electricity|Conventional|Waste-to-Energy
    ecoinvent alias:
      name: treatment of municipal solid waste, incineration
      reference product: electricity, for reuse in municipal waste incineration only
      exists in original database: True

  conventional_other:
    production volume:
      variable: Production|Electricity|Conventional|Other
    ecoinvent alias:
      name: electricity production, natural gas, combined cycle power plant
      reference product: electricity, high voltage
      exists in original database: True

  pv:
    production volume:
      variable: Production|Electricity|Renewable|Photovoltaic
    ecoinvent alias:
      name: electricity production, photovoltaic
      reference product: electricity, low voltage
      exists in original database: True

  wind:
    production volume:
      variable: Production|Electricity|Renewable|Wind turbines|Onshore
    ecoinvent alias:
      name: electricity production, wind, 1-3MW turbine, onshore
      reference product: electricity, high voltage
      exists in original database: True

  geothermal:
    production volume:
      variable: Production|Electricity|Renewable|Geothermal
    ecoinvent alias:
      name: electricity production, deep geothermal
      reference product: electricity, high voltage
      exists in original database: True

  biomass:
    production volume:
      variable: Production|Electricity|Renewable|Biomass
    ecoinvent alias:
      name: heat and power co-generation, wood chips, 6667 kW
      reference product: electricity, high voltage
      exists in original database: True

  biogas:
    production volume:
      variable: Production|Electricity|Renewable|Biogas
    ecoinvent alias:
      name: heat and power co-generation, biogas, gas engine
      reference product: electricity, high voltage
      exists in original database: True

  import:
    production volume:
      variable: Production|Electricity|Import
    ecoinvent alias:
      name: market group for electricity, high voltage
      reference product: electricity, high voltage
      exists in original database: False
      new dataset: True

  medium_to_high:
    production volume:
      variable: Production|Electricity|Medium to high
    ecoinvent alias:
      name: market for electricity, high voltage, EP2050
      reference product: electricity, high voltage
      exists in original database: False
      new dataset: True

  low_to_medium:
    production volume:
      variable: Production|Electricity|Low to medium
    ecoinvent alias:
      name: market for electricity, medium voltage, EP2050
      reference product: electricity, medium voltage
      exists in original database: False
      new dataset: True

  Wind_offshore:
    production volume:
      variable: Production|Electricity|Wind|Offshore
    ecoinvent alias:
      name: electricity production, wind, 1-3MW turbine, offshore
      reference product: electricity, high voltage
      exists in original database: True

  Lignite:
    production volume:
      variable: Production|Electricity|Lignite
    ecoinvent alias:
      name: electricity production, lignite
      reference product: electricity, high voltage
      exists in original database: True
  
  Hard_coal:
    production volume:
      variable: Production|Electricity|Hard_coal
    ecoinvent alias:
      name: heat and power co-generation, hard coal
      reference product: electricity, high voltage
      exists in original database: True

  Natural_gas:
    production volume:
      variable: Production|Electricity|Natural_gas
    ecoinvent alias:
      name: electricity production, natural gas, combined cycle power plant
      reference product: electricity, high voltage
      exists in original database: True

  Heat_Natural_gas:
    production volume:
      variable: Production|Heat|Gas
    ecoinvent alias:
      name: heat production, natural gas, at industrial furnace >100kW
      reference product: heat, district or industrial, natural gas
      exists in original database: True

  Heat_Oil:
    production volume:
      variable: Production|Heat|Oil
    ecoinvent alias:
      name: heat production, light fuel oil, at industrial furnace 1MW
      reference product: heat, district or industrial, other than natural gas
      exists in original database: True

  Heat_Coal:
    production volume:
      variable: Production|Heat|Coal
    ecoinvent alias:
      name: heat production, at hard coal industrial furnace 1-10MW
      reference product: heat, district or industrial, other than natural gas
      exists in original database: True

  Heat_Biomass:
    production volume:
      variable: Production|Heat|Biomass
    ecoinvent alias: 
      name: heat and power co-generation, wood chips, 6667 kW, state-of-the-art 2014
      reference product: heat, district or industrial, other than natural gas
      exists in original database: True

  Heat_Electricty:
    production volume:
      variable: Production|Heat|Electricity
    ecoinvent alias: 
      name: Heat, from electricity
      reference product: process heat
      exists in original database: False 

  Heat_Hydrogen_input:
    production volume:
      variable: Production|Heat|Hydrogen_input
    ecoinvent alias: 
      name: hydrogen production, gaseous, 25 bar, from electrolysis
      reference product: Hydrogen, gaseous, 25 bar
      exists in original database: True
    replaces: 
      - name: market for biomethane
    replaces in:
      - name: heat production, biomethane, at boiler condensing modulating <100kW
    substitution ratio: 0.282225

  Heat_Hydrogen:
    production volume:
      variable: Production|Heat|Hydrogen
    ecoinvent alias: 
      name: heat production, biomethane, at boiler condensing modulating <100kW
      reference product: heat, central or small-scale, biomethane
      exists in original database: True

  Heat_CHP:
    production volume:
      variable: Production|Heat|CHP
    ecoinvent alias: 
      name: heat and power co-generation, natural gas, conventional power plant, 100MW electrical
      reference product: heat, district or industrial, natural gas
      exists in original database: True

  
markets:

  - name: market for electricity, high voltage, DE20_25_30
    reference product: electricity, high voltage
    unit: kilowatt hour
    includes:
      - hydro_run_of_river
      - hydro_reservoir
      - nuclear_boiling_water
      - nuclear_pressure_water
      - conventional_waste
      - conventional_other
      - pv
      - wind
      - geothermal
      - biomass
      - biogas
      - import
      - Hard_coal
      - Lignite
      - Wind_offshore
      - Natural_gas

    add:
      - name: transmission network construction, long-distance
        reference product: transmission network, long-distance
        amount: 3.17e-10

      - name: transmission network construction, electricity, high voltage
        reference product: transmission network, electricity, high voltage
        amount: 6.58e-09

      - name: Dinitrogen monoxide
        categories: air
        unit: kilogram
        amount: 5.0e-06

      - name: Ozone
        categories: air
        unit: kilogram
        amount: 4.16e-06

    replaces:
      - name: market for electricity, high voltage
        product: electricity, high voltage
        location: DE

    replaces in:
      - location: DE

    except regions:
      - World

  - name: market for electricity, medium voltage, DE_20_25_30
    reference product: electricity, medium voltage
    unit: kilowatt hour
    includes:
      - medium_to_high

    add:
      - name: market for sulfur hexafluoride, liquid
        reference product: sulfur hexafluoride, liquid
        amount: 5.4e-08

      - name: transmission network construction, electricity, medium voltage
        reference product: transmission network, electricity, medium voltage
        amount: 1.86e-08

      - name: Sulfur hexafluoride
        categories: air
        unit: kilogram
        amount: 5.4e-08

    efficiency:
      - variable: Transmission losses|Electricity|Medium to high

    replaces:
      - name: market for electricity, medium voltage
        product: electricity, medium voltage
        location: DE

    replaces in:
      - location: DE

    except regions:
      - World

  - name: market for electricity, low voltage, DE20_25_30
    reference product: electricity, low voltage
    unit: kilowatt hour
    includes:
      - low_to_medium

    add:
      - name: market for sulfur hexafluoride, liquid
        reference product: sulfur hexafluoride, liquid
        amount: 2.99e-09

      - name: distribution network construction, electricity, low voltage
        reference product: distribution network, electricity, low voltage
        amount: 8.74e-08

      - name: Sulfur hexafluoride
        categories: air
        unit: kilogram
        amount: 2.99e-09

    efficiency:
      - variable: Distribution losses|Electricity|Low to medium

    replaces:
      - name: market for electricity, low voltage
        product: electricity, low voltage
        location: DE

    replaces in:
      - location: DE

    except regions:
      - World

- name: market for process heat, DE20_25_30
    reference product: process heat
    unit: megajoule
    includes:
      - Hard coal
      - Oil
      - Natural gas
      - Biomass
      - CHP
      - Electricity
      - Hydrogen
      

    except regions:
      - World