name: Github Action
on: [push, pull_request]

jobs:

  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v7
        with:
          default: 3.9.0
          command: pip install -U pip  # upgrade pip after installing python

      - name: create environment
        run: pyenv local 3.9.0 && python -mvenv .venv390

      - name: Install dependencies
        run: |
          pip install -r requirements.txt --upgrade pip
          pip install pytest

      - name: Run tests
        run: pytest

  release:
    name: Create Release
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: fetch version
        run: VERSION=$(python version.py --version)

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v.VERSION
          release_name: v.VERSION
          body: Scenario update
          draft: false
          prerelease: false
