name: Github Action
on: [push, pull_request]

jobs:

  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v7
        with:
          default: 3.9.0
          command: pip install -U pip  # upgrade pip after installing python

      - name: create environment
        run: pyenv local 3.9.0 && python -mvenv .venv390

      - name: Install dependencies
        run: |
          pip install -r requirements.txt --upgrade pip
          pip install pytest

      - name: Run tests
        run: pytest


  release:
    name: Create Release
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
